version: 1
formatters:
  simple:
    format: '%(asctime)s - %(levelname)s - %(message)s'
handlers:
  console:
    class: logging.StreamHandler
    formatter: brief
    stream: ext://sys.stdout
  file:
    class: logging.handlers.RotatingFileHandler
    formatter: precise
    filename: ~/.config/simple-alarm/logs/simple-alarm.log
    maxBytes: 4096
    backupCount: 3
root:
  level: NOTSET
  handlers: [console]
loggers:
  mainLogger:
    level: debug
    handlers: [console]

